services:
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=picpaydb
      - MYSQL_ROOT_PASSWORD=Mysql1262
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: